10の課題完了
k-iwashita-prtimes/kenshu-frontend-js-public pull request #10
Opened 2021-03-22 03:05 UTC by k-iwashita-prtimes

2021-03-26 04:02 UTC, pr-YudaiSuzuki requested changes
細かいですが、`next` 中に `prev` 、もしくは `prev` 中に `next` をクリックすると意図せぬ動作となります。

確認して修正してみてください。
この課題は少し難易度が高いので、行き詰まったら`example` を参考にしてみてください。

2021-03-26 05:36 UTC, k-iwashita-prtimes commented
もう一度修正するので、レビューはまだ大丈夫です！

2021-03-26 06:07 UTC, k-iwashita-prtimes commented
レビューお願いします！

2021-03-26 09:38 UTC, pr-YudaiSuzuki requested changes
`isTransition` フラグや `Promise` などを使う着眼点はとても良いと思います！
ただ、もう少し改善できる点があるのでコメントを参考に改善してみてください。

2021-03-26 09:38 UTC, pr-YudaiSuzuki commented on practice/10/try/src/js/index.js
> +  const isTransitioning = { transition: "finished" };
こちらの変数ですが、`let` で変数定義して `isTransitioning` を Boolean で管理すれば十分かと思います。そうすることで `if` 文もすっきり書くことができますし、状態の名前をいちいち確認する必要がなくなります。

2021-03-26 09:38 UTC, pr-YudaiSuzuki commented on practice/10/try/src/js/index.js
> +    }
こちら、全ての処理が `isTransitioning` の状態に依存しているので、Early return を使ってあげるとネストが少なくなりすっきりとしたコードになるかと思います。

2021-03-26 09:38 UTC, pr-YudaiSuzuki commented on practice/10/try/src/js/index.js
> +    }
こちらも同じく Early return を使ってみると良いでしょう。

2021-03-26 09:38 UTC, pr-YudaiSuzuki commented on practice/10/try/src/js/index.js
> +      });
`Promise` を使う視点はとても良いと思いますが、`transitionend` イベント自体が「トランジション処理が完了したら」という意味を持っているので、こちらの最後に  `setIsTransition()` の処理を追加しても問題なく動作すると思います。

2021-03-29 09:38 UTC, pr-YudaiSuzuki approved these changes
LGTMです！

2021-03-30 02:38 UTC, closed without merging